// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TripPlanner.Data;

#nullable disable

namespace TripPlanner.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryLanguage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("CountryId");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryLanguage = "English",
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryLanguage = "Persian (Farsi)",
                            CountryName = "Iran"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryLanguage = "Mandarin (Simplify Chinese)",
                            CountryName = "China"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryLanguage = "Mandarin (Traditional Chinese)",
                            CountryName = "Taiwan"
                        });
                });

            modelBuilder.Entity("TripPlanner.Models.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("itinerary_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("itineraries", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Models.ItineraryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StopOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("LocationId");

                    b.ToTable("itinerary_items", (string)null);
                });

            modelBuilder.Entity("TripPlanner.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaceId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "290 Bremner Blvd, Toronto, ON M5V 3L9",
                            Latitude = 43.6425662m,
                            Longitude = -79.3870568m,
                            Name = "CN Tower"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Isfahan, Isfahan Province, Iran",
                            Latitude = 32.65745m,
                            Longitude = 51.677778m,
                            Name = "Naqsh-e Jahan Square"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Yuchi Township, Nantou County, Taiwan",
                            Latitude = 23.866667m,
                            Longitude = 120.916667m,
                            Name = "Sun Moon Lake"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Tuojiang Town, Fenghuang County, Xiangxi Tujia and Miao Autonomous Prefecture of Hunan Province",
                            Latitude = 27.952822m,
                            Longitude = 109.600989m,
                            Name = "Fenghuang Ancient City"
                        },
                        new
                        {
                            Id = 5,
                            Address = "1 Austin Terrace, Toronto, ON M5R 1X8",
                            Latitude = 43.6781015m,
                            Longitude = -79.4094159m,
                            Name = "Casa Loma"
                        },
                        new
                        {
                            Id = 6,
                            Address = "1 Blue Jays Way, Toronto, ON M5V 1J4",
                            Latitude = 43.6416598m,
                            Longitude = -79.3891976m,
                            Name = "Rogers Centre"
                        },
                        new
                        {
                            Id = 7,
                            Address = "160 Kendal Ave, Toronto, ON M5R 1M3",
                            Latitude = 43.675865m,
                            Longitude = -79.4109118m,
                            Name = "George Brown Polytechnic - Casa Loma Campus"
                        },
                        new
                        {
                            Id = 8,
                            Address = "200 King St E, Toronto, ON M5A 3W8",
                            Latitude = 43.6514195m,
                            Longitude = -79.3708678m,
                            Name = "George Brown Polytechnic - St. James Campus"
                        },
                        new
                        {
                            Id = 9,
                            Address = "51 Dockside Dr, Toronto, ON M5A 0B6",
                            Latitude = 43.6441155m,
                            Longitude = -79.3656226m,
                            Name = "George Brown Polytechnic- Waterfront Campus"
                        },
                        new
                        {
                            Id = 10,
                            Address = "100 Queens Park, Toronto, ON M5S 2C6",
                            Latitude = 43.6657043m,
                            Longitude = -79.3939679m,
                            Name = "Royal Ontario Museum"
                        },
                        new
                        {
                            Id = 11,
                            Address = "317 Dundas St W, Toronto, ON M5T 1G4",
                            Latitude = 43.6536066m,
                            Longitude = -79.3925123m,
                            Name = "Art Gallery of Ontario"
                        },
                        new
                        {
                            Id = 12,
                            Address = "288 Bremner Blvd, Toronto, ON M5V 3L9",
                            Latitude = 43.6424036m,
                            Longitude = -79.3868690m,
                            Name = "Ripley's Aquarium of Canada"
                        },
                        new
                        {
                            Id = 13,
                            Address = "6650 Niagara Pkwy, Niagara Falls, ON L2G 0L0",
                            Latitude = 43.0799120m,
                            Longitude = -79.0746950m,
                            Name = "Niagara Falls (Horseshoe Falls)"
                        },
                        new
                        {
                            Id = 14,
                            Address = "111 Wellington St, Ottawa, ON K1A 0A9",
                            Latitude = 45.4235937m,
                            Longitude = -75.7009290m,
                            Name = "Parliament Hill"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Old Quebec, Quebec City, QC G1R",
                            Latitude = 46.8138783m,
                            Longitude = -71.2079809m,
                            Name = "Old Quebec (Vieux-Québec)"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Vancouver, BC V6G 1Z4",
                            Latitude = 49.3043010m,
                            Longitude = -123.1443000m,
                            Name = "Stanley Park"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Banff, AB T1L 1K2",
                            Latitude = 51.4968460m,
                            Longitude = -115.9280560m,
                            Name = "Banff National Park"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TripPlanner.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TripPlanner.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripPlanner.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TripPlanner.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TripPlanner.Models.Itinerary", b =>
                {
                    b.HasOne("TripPlanner.Models.Country", "Country")
                        .WithMany("Itineraries")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TripPlanner.Models.ApplicationUser", "User")
                        .WithMany("Itineraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripPlanner.Models.ItineraryItem", b =>
                {
                    b.HasOne("TripPlanner.Models.Itinerary", "Itinerary")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripPlanner.Models.Location", "Location")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Itinerary");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TripPlanner.Models.ApplicationUser", b =>
                {
                    b.Navigation("Itineraries");
                });

            modelBuilder.Entity("TripPlanner.Models.Country", b =>
                {
                    b.Navigation("Itineraries");
                });

            modelBuilder.Entity("TripPlanner.Models.Itinerary", b =>
                {
                    b.Navigation("ItineraryItems");
                });

            modelBuilder.Entity("TripPlanner.Models.Location", b =>
                {
                    b.Navigation("ItineraryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
